# Generated by Django 5.2.3 on 2025-07-06 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('feature_generator', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('back', 'Back'), ('lay', 'Lay')], max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'BetModel',
                'verbose_name_plural': 'BetModels',
                'db_table': 'bet_models',
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('source', models.CharField(choices=[('exchange', 'Exchange'), ('bookie', 'Bookie')], max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('home', models.CharField(max_length=100)),
                ('away', models.CharField(max_length=100)),
                ('home_ht_score', models.IntegerField(null=True)),
                ('away_ht_score', models.IntegerField(null=True)),
                ('home_ft_score', models.IntegerField(null=True)),
                ('away_ft_score', models.IntegerField(null=True)),
                ('home_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('draw_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('away_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('over_25_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('under_25_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('btts_yes_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('btts_no_odds', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Fixture',
                'verbose_name_plural': 'Fixtures',
                'db_table': 'fixtures',
                'ordering': ['date', 'time'],
                'indexes': [models.Index(fields=['date'], name='fixtures_date_c35186_idx'), models.Index(fields=['date', 'source'], name='fixtures_date_262205_idx')],
                'unique_together': {('date', 'source', 'home', 'away')},
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result', models.CharField(choices=[('green', 'Green'), ('red', 'Red'), ('void', 'Void')], max_length=10)),
                ('bet_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='rest_api.betmodel')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='rest_api.fixture')),
            ],
            options={
                'verbose_name': 'Bet',
                'verbose_name_plural': 'Bets',
                'db_table': 'bets',
                'indexes': [models.Index(fields=['bet_model'], name='bets_bet_mod_04efa2_idx')],
            },
        ),
    ]
